version: '3'

networks:
  recyclarr:
    name: recyclarr

volumes:
  radarr1:
  radarr2:
  sonarr1:

services:
  radarr1:
    image: ghcr.io/hotio/radarr
    networks:
      recyclarr:
        aliases:
          - radarr1
    ports:
      - 7878:7878
    volumes:
      - radarr1:/config
      - ./certs:/certs:ro
    environment:
      - TZ=America/Chicago

  radarr2:
    image: ghcr.io/hotio/radarr:nightly
    networks:
      recyclarr:
        aliases:
          - radarr2
    ports:
      - 6767:7878
    volumes:
      - radarr2:/config
    environment:
      - TZ=America/Chicago

  sonarr1:
    image: ghcr.io/hotio/sonarr:nightly
    networks:
      recyclarr:
        aliases:
          - sonarr1
    ports:
      - 8989:8989
    volumes:
      - sonarr1:/config
    environment:
      - TZ=America/Chicago
