version: '3'

networks:
  recyclarr:
    name: recyclarr
    external: true

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    # user: $DOCKER_UID:$DOCKER_GID
    build:
      context: .
      args:
        - TARGETPLATFORM=linux/amd64
        - BUILD_FROM_BRANCH=fix-rootless-docker
    init: true
    networks: [recyclarr]
    volumes:
      - ./config:/config
    environment:
      RECYCLARR_INTERVAL: 1d
      TZ: America/Chicago
